CREATE TABLE CURTULEFACILITY(
		CULTUREFNO                    		NUMBER(10)		 NOT NULL		 PRIMARY KEY,
		CNAME                         		VARCHAR2(200)		 NOT NULL,
		LATITUDE                      		VARCHAR2(10)		 NOT NULL,
		LONGITUDE                     		VARCHAR2(10)		 NOT NULL,
		ADDR_CODE                     		VARCHAR2(10)		 NOT NULL,
		PHONE                         		VARCHAR2(15)		 NOT NULL,
		CLOSEDDAYS                    		DATE		 NOT NULL,
		OPERATINGTIME                 		VARCHAR2(30)		 NOT NULL,
		PA                            		VARCHAR2(10)		 NOT NULL,
		MASTERNO                      		NUMBER(10)		 NULL ,
  FOREIGN KEY (MASTERNO) REFERENCES MASTER (MASTERNO)
);

COMMENT ON TABLE CURTULEFACILITY is '문화시설';
COMMENT ON COLUMN CURTULEFACILITY.CULTUREFNO is '문화시설번호';
COMMENT ON COLUMN CURTULEFACILITY.CNAME is '문화시설이름';
COMMENT ON COLUMN CURTULEFACILITY.LATITUDE is '위도';
COMMENT ON COLUMN CURTULEFACILITY.LONGITUDE is '경도';
COMMENT ON COLUMN CURTULEFACILITY.ADDR_CODE is '우편번호';
COMMENT ON COLUMN CURTULEFACILITY.PHONE is '전화번호';
COMMENT ON COLUMN CURTULEFACILITY.CLOSEDDAYS is '휴무일';
COMMENT ON COLUMN CURTULEFACILITY.OPERATINGTIME is '운영시간';
COMMENT ON COLUMN CURTULEFACILITY.PA is '주차가능여부';
COMMENT ON COLUMN CURTULEFACILITY.MASTERNO is '관리자번호';